### ISSUE TITLE
Support for Cobalt Strike HTTP Host Profiles

### ISSUE THREAD

**Issue by pwnf** [D00Movenok/BounceBack#16]
**Is your feature request related to a problem? Please describe. **
I am trying to run BounceBack using a Cobalt Strike profile that includes a 'http-host-profiles' block, and it appears unsupported.

**Describe the solution you'd like**
Host profiles allow for differing URI's and variability in HTTP/S C2 within Cobalt Strike i.e. a profile variation is used based on the hostname being used at the time and allows for additional headers or parameters to be added as well as supporting a dynamic syntax for variation within the host profile itself. Ideally, BounceBack would support Host profiles. This would involve parsing the http-host-profiles block and factoring in any of the dynamic syntax into its malleable rule generation.

**Describe alternatives you've considered**
The alternatives would be to not use BounceBack and continue using something like Apache or Nginx as the benefit of host profiles is desired.

**Additional context**

Here's a screenshot of the error message:
![image](https://github.com/user-attachments/assets/97d618df-5b61-4fed-bd92-466d6aaa8dc3)

Here is a link to the documentation describing host profiles and the dynamic syntax that can be used within a host profile:

https://hstechdocs.helpsystems.com/manuals/cobaltstrike/current/userguide/content/topics/malleable-c2_http-host-profiles.htm

**Comment by D00Movenok** [comment]
Thanks for your report!

Yeah, looks like I fully missed that section in the parser.

I'll try to fix that bug in the near future.

Please, let me know, if you find other bugs.

**Comment by D00Movenok** [comment]
> If the blue team is investigating domain1.cdn.com I would like to be able to proxy them to somedomain.com or if they are investigating domin2.cdn.com, I'd like to be able to proxy them to someotherdomain.com such that the domain they are proxied or redirected to is relevant to the domain they are investigating..

Yeah, you probably could do it using independent proxy instances in config (one proxy - one cdn), e.g.

```yaml
proxies:
  - name: cdn 1
    type: http
    listen: 0.0.0.0:8081 <--- one listen port
    target: http://127.0.0.1:8080
    filter_settings:
      reject_action: proxy
      reject_url: https://site1.org <--- one proxy site
    **snip**
      
  - name: cdn 2
    type: http
    listen: 0.0.0.0:8082 <--- another one listen port
    target: http://127.0.0.1:8080
    filter_settings:
      reject_action: proxy
      reject_url: https://site2.org <--- another one proxy site
    **snip**
```
